using Vigia.Plugins;

namespace Vigia.Application.Agents;

/// <summary>
/// A finished probe, ready to be stored or sent to the control plane.
/// </summary>
/// <param name="Id">UUIDv7 generated by the agent; makes re-sending idempotent.</param>
/// <param name="CheckId">Check that was probed.</param>
/// <param name="Agent">Agent that ran the probe.</param>
/// <param name="Outcome">Probe outcome.</param>
/// <param name="Measurements">Dimension name to value.</param>
/// <param name="Message">Why the target is down or the probe failed.</param>
/// <param name="DurationMs">Probe duration in milliseconds.</param>
/// <param name="ObservedAt">When the probe started (UTC).</param>
public sealed record ProbeRecord(
    Guid Id,
    Guid CheckId,
    string Agent,
    Outcome Outcome,
    IReadOnlyDictionary<string, double> Measurements,
    string? Message,
    double DurationMs,
    DateTimeOffset ObservedAt);
